let adminProfile=null;
async function adminInit(){const status=document.getElementById('admin-status');try{if(!await initBackend())throw new Error('CONFIG');if(!currentUser||currentUser.role!=='admin')throw new Error('DENIED');adminProfile=currentUser;status.hidden=true;document.getElementById('admin-app').hidden=false;bindTabs();await refreshAdmin();}catch(e){status.classList.add('error');status.textContent=e.message==='CONFIG'?'Supabase غير متصل. أضف الإعدادات في js/config.js':'غير مصرح لك بفتح لوحة الإدارة. سجل الدخول بحساب Admin.';}}
function bindTabs(){document.querySelectorAll('.admin-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.admin-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');const t=b.dataset.tab;document.getElementById('admin-products').hidden=t!=='products';document.getElementById('admin-charges').hidden=t!=='charges';});}
async function refreshAdmin(){const [{data:products},{data:charges},{count:users}]=await Promise.all([db.from('products').select('*').eq('status','pending').order('created_at'),db.from('charge_requests').select('*,profiles:user_id(name,phone)').eq('status','pending').order('created_at'),db.from('profiles').select('*',{count:'exact',head:true})]);renderStats(products||[],charges||[],users||0);renderPendingProducts(products||[]);await renderCharges(charges||[]);}
function renderStats(p,c,u){document.getElementById('admin-stats').innerHTML=`<div class="stat"><span>مستخدمون</span><b>${u}</b></div><div class="stat"><span>منتجات معلقة</span><b>${p.length}</b></div><div class="stat"><span>طلبات شحن</span><b>${c.length}</b></div>`;}
function renderPendingProducts(list){const el=document.getElementById('admin-products');el.innerHTML=list.map(p=>`<article class="admin-card"><div class="admin-row"><div><b>${escapeHTML(p.name)}</b><div class="admin-meta">${escapeHTML(p.seller_name)} • ${Number(p.price).toLocaleString()} جنيه • ${escapeHTML(p.phone)}</div><div class="admin-meta">${escapeHTML(p.description||'بدون وصف')}</div></div><div class="admin-actions"><button class="admin-btn ok" onclick="reviewProduct('${p.id}','active')">قبول</button><button class="admin-btn no" onclick="reviewProduct('${p.id}','rejected')">رفض</button></div></div></article>`).join('')||'<div class="admin-card">لا توجد منتجات معلقة.</div>';}
async function reviewProduct(id,status){const {error}=await db.from('products').update({status}).eq('id',id);if(error)return alert('تعذر تنفيذ العملية');await refreshAdmin();}
async function renderCharges(list){const el=document.getElementById('admin-charges');const blocks=[];for(const r of list){let url='';const {data}=await db.storage.from('receipts').createSignedUrl(r.receipt_url,300);url=data?.signedUrl||'';blocks.push(`<article class="admin-card"><div class="admin-row"><div><b>${escapeHTML(r.profiles?.name||'مستخدم')} — ${Number(r.amount).toLocaleString()} جنيه</b><div class="admin-meta">${escapeHTML(r.profiles?.phone||'')} • ${new Date(r.created_at).toLocaleString('ar-EG')}</div>${url?`<a href="${url}" target="_blank" class="admin-btn view">فتح الإيصال</a><br><img class="receipt-img" src="${url}" alt="إيصال">`:''}</div><div class="admin-actions"><button class="admin-btn ok" onclick="reviewCharge('${r.id}',true)">اعتماد وإضافة الرصيد</button><button class="admin-btn no" onclick="reviewCharge('${r.id}',false)">رفض</button></div></div></article>`);}el.innerHTML=blocks.join('')||'<div class="admin-card">لا توجد طلبات شحن معلقة.</div>';}
async function reviewCharge(id,approve){if(!confirm(approve?'تأكيد اعتماد الشحن وإضافة الرصيد؟':'تأكيد رفض الطلب؟'))return;const {error}=await db.rpc('admin_review_charge',{p_request_id:id,p_approve:approve});if(error)return alert('تعذر تنفيذ العملية: '+error.message);await refreshAdmin();}
window.addEventListener('load',adminInit);
